# Generated by Django 4.1.1 on 2022-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Блюдо')),
                ('products', models.TextField(default='', verbose_name='Ингредиенты')),
                ('context', models.TextField(default='', verbose_name='Рецепт')),
            ],
        ),
    ]
